# Copyright 2026 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

import("../../Lynx.gni")

if (enable_wasmr) {
  lynx_core_source_set("wasmr") {
    sources = [
      "wasmr_host_functions.cc",
      "wasmr_host_functions.h",
      "wasmr_runner.cc",
      "wasmr_runner.h",
    ]
    deps = [ "../lepus/bindings:bindings" ]
    public_deps = [ "../../../third_party/wasmr:wasmr" ]
  }
} else {
  group("wasmr") {
  }
}
